### ISSUE TITLE
Have you encountered the following problem?

### ISSUE THREAD

**Issue by turingvideosjp** [spacewalk01/yolov9-face-detection#1]
File "/alg_vepfs/private/xxxxx/yolov9/utils/general.py", line 905, in non_max_suppression
    device = prediction.device
AttributeError: 'list' object has no attribute 'device'

**Comment by spacewalk01** [comment]
Yes. I've fixed it by changing it like following:

https://github.com/spacewalk01/yolov9-face-detection/blob/92956ebc9356ac6a9f29897237edfee03e97bcb4/yolov9/utils/general.py#L903

**Comment by spacewalk01** [comment]
https://github.com/WongKinYiu/yolov9/issues/11#issuecomment-1960627261
