### ISSUE TITLE
Running in Windows 10

### ISSUE THREAD

**Issue by PreWisdom** [spacewalk01/yolov9-face-detection#2]
Thx for your trained model weights.
And if anyone wants to implement this project with the Windows 10 OS. U need to change the code:
`python train2yolo.py [datasets/original-widerface/train] [datasets/widerface/train]`
`python val2yolo.py [datasets/original-widerface] [datasets/widerface/val]`
to
`python train2yolo.py datasets/original-widerface/train datasets/widerface/train`
`python val2yolo.py datasets/original-widerface datasets/widerface/val`
at Data Preparation Stage

**Comment by spacewalk01** [comment]
Yes in windows and linux both should be changed like that. I will change it in readme thanks for reminding me
